### ISSUE TITLE
トップページに使い方の説明をつける

### ISSUE THREAD

**Issue by chvmvd** [ut-code/learn-braille#40]
現在チュートリアルのページでやってるようにダイアログを作って、簡単にこのウェブサイトの使い方を説明したい。
内容としては、あまり長いと見てくれないので 20 秒ほどでみれるようにして最低限のことを説明したい。

<img width="1439" alt="スクリーンショット 2023-04-22 0 18 58" src="https://user-images.githubusercontent.com/104971044/233673664-f74c2313-360e-42ef-885c-e0c173bc2b19.png">

**Comment by chvmvd** [comment]
着想元としては、Dull Meshi 班で作っている[これ](https://dull-meshi.onrender.com/)。

https://user-images.githubusercontent.com/104971044/233674605-e08328d8-8a94-48b2-a75c-2fff863ddf89.MP4

**Comment by chvmvd** [comment]
ダイアログは、コンポーネントを作ってあるのでそれを使う感じがとりあえず良いかな。点字キーボードとか Web 点字器のコードを見たら参考になりそう。

**Comment by chvmvd** [comment]
Dull Meshi 班みたいにするとパソコンの表示には微妙なのでとりあえずダイアログで作ってみるのが良いかもです。いいアイディアがあったら、また考えましょう。

**Comment by random776** [comment]
ちなみになぜダイアログでないとダメなんですか？
私的にはトップページのボタンの下に簡単に書いておく方が見やすい気がしています。

**Comment by chvmvd** [comment]
たしかに！
そもそも、使い方の説明はなくてよいか。見れば、わかるし。

**Comment by random776** [comment]
ただ、簡単にそれぞれのページが何をするページかということは簡単に書いておいた方がいいと思います！

**Comment by chvmvd** [comment]
そうだね。
そしたら、あの Card をちょっと編集して内容を見れるようにしてもらえる？

**Comment by chvmvd** [comment]
https://mui.com/material-ui/react-card/ こんな感じで。

**Comment by chvmvd** [comment]
Fixed with #43
