### ISSUE TITLE
keyboardで点字列の中身を編集できるようにしたい。

### ISSUE THREAD

**Issue by brdgb** [ut-code/learn-braille#82]
現状点字列の末尾でしか点字を追加、削除ができない。
カーソル位置で追加、削除できるようにしたいが、Textareaのカーソルの位置の取得方法がよくわからず、困っている。

**Comment by chvmvd** [comment]
これは、僕も困っています。一応、頑張って取得すれば作れるには作れるとは思ってますが、キーボードでカーソルを動かす場合、マウスで動かす場合、…と無限に対応しないといけないので限界を感じてます。後は、選択して削除とかもありますからね。
普通のテキストボックスの機能にそこらへんはお任せできないか検討中って感じです…正直、けっこう悩んでます。
